FROM node:14-alpine

WORKDIR /app

# Bundle app source
COPY . /app/

# install packages
RUN yarn install --production

# Build Angular app
WORKDIR /app/frontend
RUN yarn install --production
RUN yarn build

# Go back to app root
WORKDIR /app

# copy react build files
RUN mv /app/frontend/build/* /app/public
