FROM node:14-alpine

# setup global packages
RUN yarn global add @angular/cli

WORKDIR /app

# Bundle app source
COPY . /app/

# install packages
RUN yarn install --production

# Build Angular app
WORKDIR /app/frontend
RUN yarn install
RUN mkdir -p ./src/environments
RUN node ../docker/setup.js
RUN yarn build

# Go back to app root
WORKDIR /app

# copy react build files
RUN mv /app/frontend/build/* /app/public
RUN node /app/docker/build-frontend.js
RUN rm /app/.env
