version: '3.3'

services:
    app:
        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
            - ${TEST_PORT}:${TEST_PORT}
        environment:
            NODE_ENV: ${NODE_ENV}
            NODE_OPTIONS: ${NODE_OPTIONS}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
            APP_SESSION_KEY: ${APP_SESSION_KEY}
            APP_USE_HTTPS: ${APP_USE_HTTPS}
            APP_PUBLIC_URL: ${APP_PUBLIC_URL}
            APP_NAME: ${APP_NAME}
            APP_DESC: ${APP_DESC}
            APP_START_URL: ${APP_START_URL}
            APP_THEME_COLOR: ${APP_THEME_COLOR}
            APP_BACKGROUND_COLOR: ${APP_BACKGROUND_COLOR}
            FRONTEND_PORT: ${FRONTEND_PORT}
            TEST_PORT: ${TEST_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATA: ${DB_DATA}
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
    db_data:
