version: '3.3'
services:
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.dev
        command: yarn all
        volumes:
            - ..:/app
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
            - ${TEST_PORT}:${TEST_PORT}
        environment:
            DB_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATA}?authSource=admin
