version: '3.3'

services:
    app:
        ports:
            - ${APP_PORT}:${APP_PORT}
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        environment:
            NODE_ENV: ${APP_ENV}
            APP_ENV: ${APP_ENV}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
            APP_PUBLIC_URL: ${APP_PUBLIC_URL}
            APP_NAME: ${APP_NAME}
            APP_DESC: ${APP_DESC}
            APP_START_URL: ${APP_START_URL}
            APP_THEME_COLOR: ${APP_THEME_COLOR}
            APP_BACKGROUND_COLOR: ${APP_BACKGROUND_COLOR}
            FRONTEND_PORT: ${FRONTEND_PORT}
